jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  application:
    name: emojinious-backend
  profiles:
    active: dev
  data:
    redis:
      #      host: ENC(+wbrYVQvJOCGwJb04tH8kHm1FNZkNNw4Zc0lokyjSddSQHjC6fr24hkZhCeuZQCQwKAV0R2eaSwUzjzmkm3o2DSvxT1Upw/3)
      #      port: 15733
      #      password: ENC(dbtRPEzugAJK7jIuKNgFhX097hSLYZsXBhoxlJGMDhaf6IQ+mHdEppU7leiQKM8V)
      host: redis-10815.c17.us-east-1-4.ec2.redns.redis-cloud.com
      port: 10815
      password: IpEQsQFHhqT0MeBteB3Fa8AjtAC4ByuQ
      ssl:
        enabled: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static

openai:
  api-key: ENC(SC6Ru637m5bGB8Vwo61PIGrjP+7YGwvAcIiXNIK7rVu2z+R+T8uKv7jONzkFQd2OGzO3vwDtYC2uxwHP7R8U0NUQapEK55heGtsT/l6FQlZrekhy/GLFJlaGoeUWYTiwQBtCdSBFMKxyLBPdcmMVXmu8iTcWOYfVhNuJ/XJLEnf0fEE+3rLbRs2mYxwcNoZ2)

jwt:
  secret: ENC(U1iEDPMT18taS96ZUvkQO8XEoJdjftoiSiFgPYEwfUlNP1oNRPK8MtC5WbPhipG4+/Ygoh7CGqx4NXtJcigdNk71liILkPbB0e8oQvWccaE=)
  expiration: 3600000

server:
  port: 8080

logging:
  level:
    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.messaging: TRACE
#    org.springframework.web.socket: TRACE
#    com.emojinious: DEBUG